name: "Deploy to CGC"
on:
  release:
    types: [released, edited]
jobs:
  cgc:
    runs-on: ubuntu-20.04
    name: "Deploy"
    steps:
      - uses: actions/checkout@v2
      - name: Set the docker tag from Repo Tag
        id: set_dockertag
        env:
          IMAGE: cgc-images.sbgenomics.com/stjude/rnapeg
          VERSION_TAG: ${{ github.event.release.tag_name }}
        run: |
          jq --arg image "${{ env.IMAGE }}:${{ env.VERSION_TAG }}" '(.requirements | .[] | select(.class == ("DockerRequirement")) | .dockerPull) |= $image' cgc/rnapeg.cwl > cgc/rnapeg.cwl.new
          mv cgc/rnapeg.cwl.new cgc/rnapeg.cwl
          cat cgc/rnapeg.cwl
      - id: cgcdeploy
        uses: stjudecloud/cgc-go@v0.1.4
        with:
          file_location: "cgc/rnapeg.cwl"
          shortid: "stjude/rnapeg/rnapeg"
          devkey: ${{ secrets.CGC_TOKEN }}
        env: 
          CGC_TOKEN: ${{ secrets.CGC_TOKEN }}
